menu:
- {name: 'Research', url: '/research'}
- {name: 'CV', url: '/assets/pdf/CV_ZH.pdf'}
- {name: 'Resume', url: '/assets/pdf/Resume_ZH.pdf'}
- {name: 'Teaching', url: '/teaching'}

social:
- {icon: 'github', link: 'https://github.com/z-y-huang'}